# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/twilight/twilight:14/UKG3.241022.001/V816.0.25.2.11.UZFAABX:user/release-keys
# TV Box S (3rd Gen) twilight / MiTV-AFMU0 / MDZ-32-AA

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "twilight"         # The product code. May be same as device code or model code.
device: "twilight"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UKG3.241022.001"       # Example: RKQ1.211119.001
incremental: "V816.0.25.2.11.UZFAABX"     # Example: 2206131341
model: "MiTV-AFMU0"           # The model code. (e.g. SM-T380)
