# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# XIAOMI TV A 2025
# https://4pda.to/forum/index.php?showtopic=1092438

oem: "google"             # The company that made your device (e.g. Samsung)
product: "kirkwood"         # The product code. May be same as device code or model code.
device: "kirkwood"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UTT3.240625.001.K5"       # Example: RKQ1.211119.001
incremental: "12147201"     # Example: 2206131341
model: "Google Google TV Streamer"           # The model code. (e.g. SM-T380)
