# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/jaws/jaws:11/RTT0.211222.001/772:user/release-keys
# TV Box S 2nd Gen (MDZ-28-AA)

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "jaws"         # The product code. May be same as device code or model code.
device: "jaws"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTT0.211222.001"       # Example: RKQ1.211119.001
incremental: "773"     # Example: 2206131341
model: "MiTV-AFKR0"           # The model code. (e.g. SM-T380)
