# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# MI TV Q2 50" 55" (mb 65") MOOR0/venom

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "venom"         # The product code. May be same as device code or model code.
device: "venom"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTT2.220301.001"       # Example: RKQ1.211119.001
incremental: "155"     # Example: 2206131341
model: "MiTV-MOOR0"           # The model code. (e.g. SM-T380)
