# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/ladybird/ladybird:14/UKM3.240326.001/490:user/release-keys
# Xiaomi TV S Mini led 2025

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "ladybird"         # The product code. May be same as device code or model code.
device: "ladybird"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UKM3.240326.001"       # Example: RKQ1.211119.001
incremental: "490"     # Example: 2206131341
model: "MiTV-MOEU0"           # The model code. (e.g. SM-T380)
