# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/tarzan/tarzan:11/RTM4.220307.164/8277:user/release-keys
# MI TV A2 MOOQ1(tarzan) 4k L43M7-EARU, L50M7-EARU, L55M7-EARU

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "tarzan"         # The product code. May be same as device code or model code.
device: "tarzan"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTM4.220307.164"       # Example: RKQ1.211119.001
incremental: "8277"     # Example: 2206131341
model: "MiTV-MOOQ1"           # The model code. (e.g. SM-T380)
