# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/volver/volver:11/RTT2.211214.001/933:user/release-keys
# Mi TV P1; MSSP2(volver): 32" L32M6-6ARG/EU

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "volver"         # The product code. May be same as device code or model code.
device: "volver"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTT2.211214.001"       # Example: RKQ1.211119.001
incremental: "933"     # Example: 2206131341
model: "MiTV-MSSP2"           # The model code. (e.g. SM-T380)
