# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# XIAOMI TV A 2025
# https://4pda.to/forum/index.php?showtopic=1092438

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "flipped"         # The product code. May be same as device code or model code.
device: "venom"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTM5.220609.003"       # Example: RKQ1.211119.001
incremental: "1850"     # Example: 2206131341
model: "MiTV-MOOR2"           # The model code. (e.g. SM-T380)
