# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/croods/croods:11/RTM4.220307.164/8313:user/release-keys
# MiTV P1 MOOQ0(croods): 43" L43M6-6ARG/EU, 50" L50M6-6ARG/EU, 55" L55M6-6ARG/EU

oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "croods"         # The product code. May be same as device code or model code.
device: "croods"          # The device code. May be same as model code.
android_version: "11" # Only put in the major version number.
build_tag: "RTM4.220307.164"       # Example: RKQ1.211119.001
incremental: "8313"     # Example: 2206131341
model: "MiTV-MOOQ0"           # The model code. (e.g. SM-T380)
