# Configure this correctly. Otherwise, the prober will not succeed in getting OTA URLs!
# All Android fingerprints follow the following format:
#   <oem>/<product>/<device>:<android_version>/<build_tag>/<incremental>:user/release-keys
# Xiaomi/lalaland/lalaland:14/UKN1.240806.017/V816.0.25.5.13.6.UOEMBTV:user/release-keys
# https://4pda.to/forum/index.php?showtopic=1102774


oem: "Xiaomi"             # The company that made your device (e.g. Samsung)
product: "lalaland"         # The product code. May be same as device code or model code.
device: "lalaland"          # The device code. May be same as model code.
android_version: "14" # Only put in the major version number.
build_tag: "UKM3.240326.001"       # Example: RKQ1.211119.001
incremental: "V816.0.25.5.13.6.UOEMBTV"     # Example: 2206131341
model: "MiTV-MOEU1"           # The model code. (e.g. SM-T380)
